# Generated by Django 3.0.5 on 2021-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
