# Generated by Django 3.0.5 on 2021-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_is_loggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
