# Generated by Django 3.0.5 on 2021-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(),
        ),
    ]
