# Generated by Django 3.0.5 on 2021-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210529_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
